const kinds={Ork:{names:["Snaga Żelazny Ząb","Gorbag z Czerwonej Doliny","Uglúk Czarnoręki"],category:"Orkowie"},Goblin:{names:["Skrzek z Tuneli","Mały Krzywus","Grishka"],category:"Orkowie"},Bestia:{names:["Szary Warg","Dzik z Czarnej Puszczy"],category:"Wilki i bestie"},Upiór:{names:["Cień Kurhanu","Zimny Szept"],category:"Upiory"},Człowiek:{names:["Bereg Łamacz Tarcz","Hild Córka Wrzosów"],category:"Źli ludzie"}};
const tiers={"Słaby":[2,8,1,2,0,1],"Standardowy":[4,16,1,4,1,2],"Elitarny":[6,24,2,6,2,3],"Przywódca":[8,48,2,8,3,4]};
const t=(name,category,kind,f,e,m,r,p,a,attack,traits)=>({id:"book-"+name.toLowerCase().replaceAll(/[^a-ząćęłńóśźż0-9]+/gi,"-"),name,category,kind,fierceness:f,endurance:e,maxEndurance:e,might:m,hate:r,maxHate:r,parry:p,armour:a,attack,traits,source:"Podręcznik"});
const bookCatalog=[
t("Goblin – łucznik","Orkowie","Goblin",2,8,1,2,0,1,"Rogowy łuk 3 (3/14, Celny Atak), Wyszczerbiony nóż 2 (2/14)","Bojaźliwość. Pod wpływem zadania Przeraź Wroga traci 1 punkt Nienawiści.\nOrkowa Trucizna. Rana zadana jego atakiem zatruwa cel."),
t("Ork – herszt","Orkowie","Ork",5,20,1,5,3,3,"Szabla 3 (3/16), Włócznia 3 (3/14, Celny Atak)","Daleki Skok. Wydaj 1 Nienawiść, aby zaatakować Bohatera w dowolnej postawie, także Bezpiecznej.\nWężowa Szybkość. Gdy jest atakowany, wydaj 1 Nienawiść, aby Osłabić test trafienia.\nTriumfalny Wrzask. Wydaj 1 Nienawiść, aby przywrócić po 1 Nienawiści pozostałym orkom w potyczce."),
t("Ork – wartownik","Orkowie","Ork",4,16,1,4,2,3,"Szabla 3 (3/16), Włócznia 3 (3/14, Celny Atak)","—"),
t("Ork – żołdak","Orkowie","Ork",3,12,1,3,1,2,"Szabla 3 (3/16), Włócznia 2 (3/14, Celny Atak)","Bojaźliwość. Pod wpływem zadania Przeraź Wroga traci 1 punkt Nienawiści."),
t("Wielki ork – wódz","Orkowie","Ork",7,48,2,7,3,4,"Ciężka szabla 3 (5/18, Strzaskanie Tarczy), Włócznia o szerokim grocie 3 (5/16, Celny Atak)","Straszliwa Siła. Po Przełamaniu Obrony atakiem wręcz wydaj 1 Nienawiść, aby Osłabić test Pancerza celu.\nWężowa Szybkość. Gdy jest atakowany, wydaj 1 Nienawiść, aby Osłabić test trafienia.\nTriumfalny Wrzask. Wydaj 1 Nienawiść, aby przywrócić po 1 Nienawiści pozostałym orkom w potyczce."),
t("Wielki ork – obrońca","Orkowie","Ork",6,24,2,6,2,3,"Orkowy topór 3 (5/18, Strzaskanie Tarczy), Włócznia o szerokim grocie 3 (5/16, Celny Atak)","Ohydna Żywotność. Cios obniżający Wytrzymałość do zera tylko Przełamuje Obronę; jeżeli przetrwa, odzyskuje całą Wytrzymałość."),
t("Wielki troll jaskiniowy","Trolle","Bestia",10,80,2,10,-1,3,"Miażdżenie 3 (6/12, Pochwycenie), Ugryzienie 2 (6/14, Celny Atak)","Wzbudzenie Strachu. Wydaj 1 Nienawiść: wszyscy Bohaterowie w zasięgu wzroku otrzymują 2 Cienia (Groza); przerażeni nie wydają Nadziei do końca potyczki.\nGruba Skóra. Wydaj 1 Nienawiść, aby dodać 2k do testu Pancerza."),
t("Troll jaskiniowy – niuchacz","Trolle","Bestia",6,50,2,6,-1,3,"Maczuga 3 (6/16, Strzaskanie Tarczy), Ugryzienie 2 (6/14, Celny Atak)","Upodobanie do Ciemności. W ciemności jego rzuty na atak są Wzmocnione.\nStrach przed Ogniem. Traci 1 Nienawiść na początku rundy, gdy walczy z przeciwnikiem niosącym płonący przedmiot.\nGruba Skóra. Wydaj 1 Nienawiść, aby dodać 2k do testu Pancerza."),
t("Troll kamienny – łupieżca","Trolle","Bestia",8,60,2,8,0,3,"Maczuga 3 (6/16, Strzaskanie Tarczy), Miażdżenie 2 (6/12, Pochwycenie)","Nienawiść (Krasnoludy). Ataki przeciw krasnoludom są Wzmocnione.\nStraszliwa Siła. Po Przełamaniu Obrony atakiem wręcz wydaj 1 Nienawiść, aby Osłabić test Pancerza celu."),
t("Troll kamienny – wódz","Trolle","Bestia",9,70,2,9,0,3,"Maczuga 3 (6/16, Strzaskanie Tarczy), Miażdżenie 2 (6/12, Pochwycenie)","Nienawiść (Krasnoludy). Ataki przeciw krasnoludom są Wzmocnione.\nStraszliwa Siła. Po Przełamaniu Obrony atakiem wręcz wydaj 1 Nienawiść, aby Osłabić test Pancerza celu.\nTriumfalny Wrzask. Wydaj 1 Nienawiść, aby przywrócić po 1 Nienawiści pozostałym trollom w potyczce."),
t("Upiór kurhanu","Upiory","Upiór",6,24,1,6,0,3,"Pradawny miecz 3 (5/16, Celny Atak), Lodowaty dotyk 2 (6/12, Pochwycenie)","Upodobanie do Ciemności. W ciemności jego rzuty na atak są Wzmocnione.\nZłowrogie Czary. Wydaj 1 Nienawiść: Bohater otrzymuje 3 Cienia (Czarnoksięstwo); nieudana Próba Cienia lub Przygnębienie pozbawia go przytomności.\nWstręt do Słońca. Traci 1 Nienawiść w każdej turze w bezpośrednim świetle słońca."),
t("Złowroga zjawa","Upiory","Upiór",4,16,1,4,1,2,"Wyszczerbiony miecz 3 (4/16), Okrutna włócznia 2 (4/14, Celny Atak)","Upodobanie do Ciemności. W ciemności jego rzuty na atak są Wzmocnione.\nStrach przed Ogniem. Traci 1 Nienawiść na początku rundy, gdy walczy z przeciwnikiem niosącym płonący przedmiot."),
t("Istota z bagien","Upiory","Upiór",3,12,1,3,0,1,"Kły 3 (3/14, Celny Atak), Pazury 2 (3/14, Pochwycenie)","Strach przed Ogniem. Traci 1 Nienawiść na początku rundy, gdy walczy z przeciwnikiem niosącym płonący przedmiot.\nWstręt do Słońca. Traci 1 Nienawiść w każdej turze w bezpośrednim świetle słońca."),
t("Dziki wilk","Wilki i bestie","Bestia",3,12,1,3,0,1,"Kły 3 (3/14, Celny Atak)","Strach przed Ogniem. Traci 1 Nienawiść na początku rundy, gdy walczy z przeciwnikiem niosącym płonący przedmiot.\nWężowa Szybkość. Gdy jest atakowany, wydaj 1 Nienawiść, aby Osłabić test trafienia."),
t("Przewodnik watahy","Wilki i bestie","Bestia",4,16,1,4,0,1,"Kły 3 (3/14, Celny Atak)","Strach przed Ogniem. Traci 1 Nienawiść na początku rundy, gdy walczy z przeciwnikiem niosącym płonący przedmiot.\nWężowa Szybkość. Gdy jest atakowany, wydaj 1 Nienawiść, aby Osłabić test trafienia.\nTriumfalne Wycie. Wydaj 1 Nienawiść, aby przywrócić po 1 Nienawiści pozostałym wargom w potyczce."),
t("Pies Saurona","Wilki i bestie","Bestia",5,20,2,5,1,2,"Kły 3 (5/14, Celny Atak), Pazury 3 (5/14, Pochwycenie)","Śmiercionośne Uderzenie. Cele zranione przez niego Osłabiają rzut kością Działania przy ustalaniu skutków Rany.\nOhydna Żywotność. Cios obniżający Wytrzymałość do zera tylko Przełamuje Obronę; jeżeli przetrwa, odzyskuje całą Wytrzymałość.\nWzbudzenie Strachu. Wydaj 1 Nienawiść: wszyscy Bohaterowie w zasięgu wzroku otrzymują 2 Cienia (Groza)."),
t("Zbir","Źli ludzie","Człowiek",2,8,1,2,0,1,"Pałka 2 (3/12), Łuk 2 (3/14, Celny Atak)","Bojaźliwość. Pod wpływem zadania Przeraź Wroga traci 1 punkt Determinacji."),
t("Herszt bandytów","Źli ludzie","Człowiek",3,12,1,3,1,2,"Krótki miecz 3 (3/16), Łuk 2 (3/14, Celny Atak)","Triumfalny Wrzask. Wydaj 1 Determinację, aby przywrócić po 1 Determinacji pozostałym bandytom w potyczce."),
t("Rozbójnik","Źli ludzie","Człowiek",4,16,1,4,0,2,"Włócznia 3 (4/14, Celny Atak), Łuk 2 (3/14, Celny Atak)","Wężowa Szybkość. Gdy jest atakowany, wydaj 1 Determinację, aby Osłabić test trafienia."),
t("Najeźdźca z Południa","Źli ludzie","Człowiek",4,16,1,4,1,2,"Topór 3 (5/18), Krótka włócznia 2 (3/14, Celny Atak)","Wojowniczość. Wydaj 1 Determinację, aby dodać 1k i Wzmocnić rzut na atak."),
t("Mocarz z Południa","Źli ludzie","Człowiek",5,20,1,5,2,3,"Włócznia 3 (4/14, Celny Atak), Topór na długim stylisku 3 (6/18, Strzaskanie Tarczy)","Wojowniczość. Wydaj 1 Determinację, aby dodać 1k i Wzmocnić rzut na atak.")];
let battle=JSON.parse(localStorage.getItem("one-ring-battle")||"[]"),library=JSON.parse(localStorage.getItem("one-ring-library")||"[]"),activeCategory="Wszystkie";
function migrate(e){let k=e.kind||"Bestia";return {...e,kind:k,category:e.category||kinds[k]?.category||"Moje",source:e.source||"Mój szablon",fierceness:e.fierceness??3,might:e.might??1,maxEndurance:e.maxEndurance??e.endurance,maxHate:e.maxHate??e.hate}}
battle=battle.map(migrate);library=library.map(migrate);
const $=s=>document.querySelector(s),resourceName=k=>k==="Człowiek"?"Determinacja":"Nienawiść",uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random();
function setResourceHelp(kind){let name=resourceName(kind),help=$("#resource-help");$("#resource-name").textContent=name;help.setAttribute("aria-label","Wyjaśnienie "+name);help.dataset.tooltip=kind==="Człowiek"?"Mierzy wolę walki i zasób do używania specjalnych zdolności. Można wydać 1 punkt, aby dodać 1k do testu; bez punktów przeciwnik ulega Wyczerpaniu. Ludzie z Determinacją mogą się poddać.":"Mierzy wolę walki i zasób do używania specjalnych zdolności. Można wydać 1 punkt, aby dodać 1k do testu; bez punktów przeciwnik ulega Wyczerpaniu. Sługi Cienia z Nienawiścią nie poddają się."}
function completeTraits(e){let shared="";if(e.category==="Orkowie")shared="Wstręt do Słońca. Traci 1 Nienawiść w każdej turze w bezpośrednim świetle słońca.";if(e.category==="Trolle")shared="Ohydna Żywotność. Cios obniżający Wytrzymałość do zera tylko Przełamuje Obronę; jeżeli przetrwa, odzyskuje całą Wytrzymałość.\nTępota. Bohater w postawie Zapalczywej może użyć Zadania Bojowego z Zagadek; sukces odbiera trollowi Nadzieję.";if(e.category==="Upiory")shared="Nieśmiertelność. Za 1 Nienawiść unika Rany albo, gdy miałby osiągnąć 0 Wytrzymałości, odzyskuje ją całą (z wyjątkiem magicznej Zguby upiorów).\nKamienne Serce. Przeraź Wroga nie działa bez magicznego sukcesu.\nWcielona Groza. Na początku pierwszej rundy Bohaterowie w zasięgu wzroku otrzymują 3 Cienia (Groza).";if(e.category==="Wilki i bestie")shared="Daleki Skok. Wydaj 1 Nienawiść, aby zaatakować Bohatera w dowolnej postawie, także Bezpiecznej.";return [e.traits,shared].filter(Boolean).join("\n\n")}
function save(){localStorage.setItem("one-ring-battle",JSON.stringify(battle));localStorage.setItem("one-ring-library",JSON.stringify(library))}
function formatBookTraits(target,traits){let lines=traits.split("\n");target.replaceChildren(...lines.map(line=>{let row=document.createElement("span"),cut=line.indexOf(".");if(cut>=0){let name=document.createElement("em");name.textContent=line.slice(0,cut+1);row.append(name,document.createTextNode(line.slice(cut+1)))}else row.textContent=line;return row}))}
function fields(e,c){c.querySelector(".enemy-tier").textContent=(e.category||e.tier)+" · "+(e.source||"Mój szablon");c.querySelector(".enemy-name").textContent=e.name;c.querySelector(".enemy-kind").textContent=e.kind;c.querySelector(".endurance-display").textContent=e.endurance+" / "+e.maxEndurance;c.querySelector(".resource-display-label").textContent=resourceName(e.kind).toUpperCase();c.querySelector(".hate-display").textContent=e.hate+" / "+e.maxHate;c.querySelector(".fierceness-display").textContent=e.fierceness??"—";c.querySelector(".might-display").textContent=e.might??"—";c.querySelector(".parry-display").textContent=e.parry||"—";c.querySelector(".armour-display").textContent=e.armour;c.querySelector(".attack-display").textContent=e.attack;let traits=completeTraits(e)||"—",target=c.querySelector(".traits-display");if(e.source==="Podręcznik")formatBookTraits(target,traits);else target.textContent=traits}
function preset(random=true){let k=kinds[$("#kind").value],v=tiers[$("#tier").value];$("#name").value=random?k.names[Math.floor(Math.random()*k.names.length)]:$("#name").value;["fierceness","endurance","might","hate","parry","armour"].forEach((x,i)=>$("#"+x).value=v[[0,1,2,3,4,5][i]]);$("#attack").value="";$("#traits").value="";setResourceHelp($("#kind").value)}
function formEnemy(){let k=$("#kind").value;return {id:uid(),name:$("#name").value.trim(),kind:k,category:kinds[k].category,tier:$("#tier").value,fierceness:+$("#fierceness").value,endurance:+$("#endurance").value,maxEndurance:+$("#endurance").value,might:+$("#might").value,hate:+$("#hate").value,maxHate:+$("#hate").value,parry:+$("#parry").value,armour:+$("#armour").value,attack:$("#attack").value.trim(),traits:$("#traits").value.trim(),source:"Mój szablon",defeated:false}}
function addToBattle(e){battle.push({...e,id:uid(),endurance:e.maxEndurance,hate:e.maxHate,defeated:false});renderBattle()}
function renderBattle(){let list=$("#battle-list");list.innerHTML="";battle.forEach(e=>{let c=$("#battle-card-template").content.firstElementChild.cloneNode(true);c.dataset.id=e.id;c.setAttribute("aria-label","Przeciągnij nagłówek, aby zmienić kolejność: "+e.name);fields(e,c);c.classList.toggle("defeated-card",e.defeated);c.querySelector(".defeated").textContent=e.defeated?"Przywróć do walki":"Oznacz jako pokonanego";list.append(c)});$("#battle-empty").hidden=!!battle.length;$("#battle-count").textContent=battle.filter(x=>!x.defeated).length;save()}
function renderLibrary(){let q=$("#library-search").value.toLowerCase(),all=[...bookCatalog,...library],items=all.filter(e=>(activeCategory==="Wszystkie"||(activeCategory==="Moje"?e.source==="Mój szablon":e.category===activeCategory))&&(e.name+" "+e.category).toLowerCase().includes(q));$("#category-filters").querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.category===activeCategory));let list=$("#library-list");list.innerHTML="";items.forEach(e=>{let human=e.kind==="Człowiek",del=e.source==="Mój szablon"?'<button class="delete">Usuń</button>':"";list.insertAdjacentHTML("beforeend",'<article class="library-card" data-id="'+e.id+'" data-source="'+e.source+'"><p class="enemy-tier">'+e.category+" · "+e.source+'</p><h3>'+e.name+'</h3><p>'+e.kind+" · "+resourceName(e.kind)+'</p><div class="library-stats">ZAJ '+e.fierceness+" · WYT "+e.maxEndurance+" · "+(human?"DET":"NEN")+" "+e.maxHate+"<br>POT "+e.might+" · OBR "+(e.parry||"—")+" · PANC "+e.armour+'</div><div class="library-actions"><button class="add">Dodaj do walki</button><button class="edit">Wczytaj do edycji</button>'+del+"</div></article>")});$("#library-empty").hidden=!!items.length;save()}
function loadEditor(e){$("#name").value=e.name;$("#kind").value=e.kind;$("#tier").value=e.tier||"Standardowy";["fierceness","endurance","might","hate","parry","armour"].forEach(x=>$("#"+x).value=x==="endurance"?e.maxEndurance:x==="hate"?e.maxHate:e[x]);$("#attack").value=e.attack;$("#traits").value=e.traits;setResourceHelp(e.kind);document.querySelector('[data-tab="generator"]').click()}
Object.keys(kinds).forEach(k=>$("#kind").insertAdjacentHTML("beforeend","<option>"+k+"</option>"));Object.keys(tiers).forEach(x=>$("#tier").insertAdjacentHTML("beforeend","<option>"+x+"</option>"));["Wszystkie",...new Set(bookCatalog.map(x=>x.category)),"Moje"].forEach(x=>$("#category-filters").insertAdjacentHTML("beforeend",'<button data-category="'+x+'">'+x+"</button>"));preset();renderBattle();renderLibrary();
$("#tier").onchange=()=>preset(false);$("#kind").onchange=()=>preset(true);$("#randomize").onclick=()=>{let a=Object.keys(kinds),b=Object.keys(tiers);$("#kind").value=a[Math.floor(Math.random()*a.length)];$("#tier").value=b[Math.floor(Math.random()*b.length)];preset()};$("#reset-form").onclick=()=>{$("#enemy-form").reset();preset()};
$("#enemy-form").onsubmit=e=>{e.preventDefault();let x=formEnemy(),action=e.submitter?.dataset.action||"battle";library.push({...x});renderLibrary();if(action==="battle"){addToBattle(x);document.querySelector('[data-tab="battle"]').click()}else document.querySelector('[data-tab="library"]').click()};$(".tabs").onclick=e=>{if(!e.target.matches(".tab"))return;document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");$("#"+e.target.dataset.tab).classList.add("active")};
$("#battle-list").onclick=e=>{let c=e.target.closest(".battle-card");if(!c)return;let x=battle.find(v=>v.id===c.dataset.id);if(e.target.dataset.change){let s=e.target.dataset.stat,max=s==="endurance"?x.maxEndurance:x.maxHate;x[s]=Math.max(0,Math.min(max,x[s]+ +e.target.dataset.change));renderBattle()}else if(e.target.classList.contains("remove")){battle=battle.filter(v=>v.id!==x.id);renderBattle()}else if(e.target.classList.contains("clone"))addToBattle(x);else if(e.target.classList.contains("defeated")){x.defeated=!x.defeated;renderBattle()}};
new Sortable($("#battle-list"),{animation:180,handle:".card-top",draggable:".battle-card",filter:"button",preventOnFilter:false,ghostClass:"sortable-ghost",chosenClass:"sortable-chosen",fallbackClass:"sortable-fallback",forceFallback:true,fallbackOnBody:true,fallbackTolerance:4,delayOnTouchOnly:true,delay:120,swapThreshold:.65,invertSwap:true,onEnd(){let order=[...$("#battle-list").children].map(card=>card.dataset.id);battle.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));save()}});
$("#category-filters").onclick=e=>{if(e.target.matches("button")){activeCategory=e.target.dataset.category;renderLibrary()}};$("#library-search").oninput=renderLibrary;$("#library-list").onclick=e=>{let c=e.target.closest(".library-card");if(!c)return;let x=[...bookCatalog,...library].find(v=>v.id===c.dataset.id&&v.source===c.dataset.source);if(e.target.classList.contains("add")){addToBattle(x);document.querySelector('[data-tab="battle"]').click()}else if(e.target.classList.contains("edit"))loadEditor(x);else if(e.target.classList.contains("delete")){library=library.filter(v=>v.id!==x.id);renderLibrary()}};
$("#clear-battle").onclick=()=>{if(confirm("Wyczyścić aktywne starcie?")){battle=[];renderBattle()}};$("#export-data").onclick=()=>{let b=new Blob([JSON.stringify({library,battle},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="bestiariusz-srodziemia.json";a.click();URL.revokeObjectURL(a.href)};$("#import-data").onclick=()=>$("#import-file").click();$("#import-file").onchange=async e=>{let file=e.target.files[0];if(!file)return;try{let data=JSON.parse(await file.text()),entries=Array.isArray(data)?data:data.library;if(!Array.isArray(entries))throw new Error();let known=new Set(library.map(x=>[x.name,x.kind,x.maxEndurance,x.maxHate,x.attack,x.traits].join("|"))),added=0;entries.forEach(raw=>{if(!raw||typeof raw.name!=="string"||!raw.name.trim())return;let x=migrate(raw),key=[x.name,x.kind,x.maxEndurance,x.maxHate,x.attack,x.traits].join("|");if(known.has(key))return;if(library.some(item=>item.id===x.id))x.id=uid();x.source="Mój szablon";library.push(x);known.add(key);added++});save();renderLibrary();alert(added?"Dodano do biblioteki: "+added+".":"W tym pliku nie ma nowych przeciwników do dodania.")}catch{alert("Nie udało się odczytać pliku. Wybierz kopię JSON wyeksportowaną z Bestiariusza.")}finally{e.target.value=""}};
document.addEventListener("pointerdown",e=>{let button=e.target.closest(".help-tooltip"),all=document.querySelectorAll(".help-tooltip");if(e.pointerType==="touch"&&button){let opening=!button.classList.contains("is-open");all.forEach(x=>{x.classList.remove("is-open");x.setAttribute("aria-expanded","false")});if(opening){button.classList.add("is-open");button.setAttribute("aria-expanded","true")}}else if(!button)all.forEach(x=>{x.classList.remove("is-open");x.setAttribute("aria-expanded","false")})});
document.querySelectorAll(".help-tooltip").forEach(button=>{button.addEventListener("pointerenter",e=>{if(e.pointerType==="mouse")button.classList.add("is-hovered")});button.addEventListener("pointerleave",()=>button.classList.remove("is-hovered"))});
