const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  try {
    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8765');
    await page.locator('[data-tab="opponents"]').click();
    const tags = await page.locator('#category-filters button').allTextContents();
    await page.locator('[data-category="Upiory"]').click();
    const template = page.locator('.library-card').filter({has:page.getByRole('heading',{name:'Upiór kurhanu',exact:true})});
    const original = await template.textContent();
    await template.getByRole('button',{name:'Szablon',exact:true}).click();
    assert.equal(await page.locator('#kind').evaluate(n=>n.tagName),'INPUT');
    assert.equal(await page.locator('#kind').inputValue(),'Upiór');
    await page.locator('#kind').fill('Wilk');
    await page.locator('#kind-toggle').click();
    assert.deepEqual(await page.locator('#enemy-kind-options [role="option"]').allTextContents(),['Goblin','Ork','Troll','Upiór','Wilk','Człowiek']);
    await page.getByRole('option',{name:'Ork',exact:true}).click();
    assert.equal(await page.locator('#kind').inputValue(),'Ork');
    assert.equal(await page.locator('#enemy-kind-options').isVisible(),false);
    await page.locator('#kind').press('ArrowDown');
    await page.locator('#kind').press('ArrowDown');
    await page.locator('#kind').press('Enter');
    assert.equal(await page.locator('#kind').inputValue(),'Troll');
    await page.locator('#kind-toggle').click();
    await page.locator('#kind').press('Escape');
    assert.equal(await page.locator('#kind').inputValue(),'Troll');
    await page.locator('#kind-toggle').click();
    await page.locator('#name').click();
    assert.equal(await page.locator('#enemy-kind-options').isVisible(),false);
    await page.locator('#kind').fill('Upiór');
    const before = await page.locator('#enemy-form').evaluate(n=>Array.from(n.querySelectorAll('input,select,textarea')).filter(n=>n.id!=='kind').map(n=>[n.id,n.value]));
    await page.locator('#kind').fill('Duch mokradeł');
    await page.locator('#kind').blur();
    assert.deepEqual(await page.locator('#enemy-form').evaluate(n=>Array.from(n.querySelectorAll('input,select,textarea')).filter(n=>n.id!=='kind').map(n=>[n.id,n.value])),before);
    await page.locator('[data-action="library"]').click();
    const saved = await page.evaluate(()=>OneRingStore.getState().library[0]);
    assert.equal(saved.kind,'Duch mokradeł');
    assert.equal(saved.category,'Własne');
    assert.equal(saved.source,'Własne');
    assert.equal(saved.distinctiveFeatures,'Chytry, Mściwy');
    assert.equal(await page.locator('.library-card.is-saved .enemy-tier').textContent(),'Duch mokradeł · Własne');
    assert.equal(await page.locator('.library-card.is-saved .enemy-features').textContent(),'Chytry, Mściwy');
    assert.deepEqual(await page.locator('#category-filters button').allTextContents(),tags);
    await page.locator('[data-category="Upiory"]').click();
    assert.equal(await page.locator('.library-card[data-source="Własne"]').count(),0);
    assert.equal(await page.locator('.library-card[data-source="Podręcznik"]').filter({has:page.getByRole('heading',{name:'Upiór kurhanu',exact:true})}).textContent(),original);
    await page.locator('[data-category="Własne"]').click();
    await page.locator('#library-search').fill('Duch mokradeł');
    assert.equal(await page.locator('.library-card').count(),1);
    await page.locator('.library-card .edit').click();
    assert.equal(await page.locator('#kind').inputValue(),'Duch mokradeł');
    await page.locator('#tier').selectOption('Elitarny');
    assert.equal(await page.locator('#kind').inputValue(),'Duch mokradeł');
    await page.locator('#kind').fill('   ');
    await page.locator('[data-action="library"]').click();
    assert.equal(await page.evaluate(()=>OneRingStore.getState().library.length),1);
    for (let i=0;i<10;i++) {
      await page.locator('#randomize').click();
      assert.ok(['Ork','Goblin','Troll','Wilk','Upiór','Człowiek'].includes(await page.locator('#kind').inputValue()));
    }
    await page.locator('#kind').fill('Strażnik <bagien>');
    await page.locator('[data-action="battle"]').click();
    assert.equal(await page.evaluate(()=>OneRingStore.getState().battle[0].kind),'Strażnik <bagien>');
    await page.reload();
    assert.equal(await page.evaluate(()=>OneRingStore.getState().library[0].kind),'Duch mokradeł');
    await page.locator('[data-tab="opponents"]').click();
    await page.locator('[data-category="Upiory"]').click();
    await page.locator('.library-card').filter({has:page.getByRole('heading',{name:'Istota z bagien',exact:true})}).getByRole('button',{name:'Szablon',exact:true}).click();
    await page.locator('[data-action="library"]').click();
    const copy = await page.evaluate(()=>OneRingStore.getState().library.at(-1));
    assert.equal(copy.name,'Istota z bagien');
    assert.equal(copy.kind,'Upiór');
    assert.equal(copy.category,'Własne');
    await page.locator('.library-card.is-saved .edit').click();
    await page.locator('#enemy-features').fill('Zwinny, <groźny>');
    await page.locator('[data-action="library"]').click();
    const copies = await page.evaluate(()=>OneRingStore.getState().library);
    assert.equal(copies.length,4);
    assert.equal(new Set(copies.map(e=>e.id)).size,4);
    assert.equal(copies.at(-1).distinctiveFeatures,'Zwinny, <groźny>');
    assert.equal(copies.at(-2).distinctiveFeatures,'');
    assert.equal(await page.locator('.library-card.is-saved .enemy-features').textContent(),'Zwinny, <groźny>');
    await page.evaluate(()=>{const s=OneRingStore;s.restoreBackup(s.exportBackup());s.addLibrary({name:'Stary własny upiór',kind:'Zjawa',source:'Własne',category:'Upiory'});});
    await page.locator('[data-category="Upiory"]').click();
    assert.equal(await page.locator('.library-card[data-source="Własne"]').count(),0);
    await page.locator('[data-category="Upiory"]').click();
    assert.equal(await page.locator('.library-card[data-source="Własne"]').count(),5);
    await page.locator('#create-enemy').click();
    await page.locator('#kind-toggle').click();
    await page.getByRole('option',{name:'Człowiek',exact:true}).click();
    await page.locator('#kind').fill('Człowiek rozumny');
    assert.equal(await page.locator('#resource-name').textContent(),'Determinacja');
    await page.locator('#tier').selectOption('Standardowy');
    assert.equal(await page.locator('#resource-name').textContent(),'Determinacja');
    await page.locator('[data-action="library"]').click();
    assert.match(await page.locator('.library-card.is-saved .library-stats').textContent(),/DET/);
    await page.reload();
    await page.locator('[data-tab="opponents"]').click();
    await page.locator('[data-category="Własne"]').click();
    await page.locator('#library-search').fill('Człowiek rozumny');
    await page.locator('.library-card .edit').click();
    assert.equal(await page.locator('#resource-name').textContent(),'Determinacja');
    await page.locator('[data-action="battle"]').click();
    await page.locator('#map-generate').click();
    const lastEnemy = await page.evaluate(()=>OneRingStore.getState().battle.at(-1));
    assert.equal(lastEnemy.resourceType,'determination');
    await page.locator('.map-token').evaluateAll((nodes,id)=>nodes.find(n=>n.dataset.id===id).click(),lastEnemy.id);
    assert.equal(await page.locator('#map-panel [data-field="hate"] > span').textContent(),'Determinacja');
    await page.locator('[data-tab="opponents"]').click();
    await page.locator('#create-enemy').click();
    await page.locator('#kind-toggle').click();
    await page.getByRole('option',{name:'Ork',exact:true}).click();
    await page.locator('#kind').fill('Własny ork');
    assert.equal(await page.locator('#resource-name').textContent(),'Nienawiść');
    await page.locator('#randomize').click();
    const randomResource = await page.locator('#resource-name').textContent();
    await page.locator('#kind').fill('Dowolny rodzaj');
    assert.equal(await page.locator('#resource-name').textContent(),randomResource);
    assert.deepEqual(errors,[]);
    console.log('Free-text enemy kind passed');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
