/* Isolated full-sheet persistence and responsive browser check. */
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8765');
    await page.locator('[data-tab="heroes"]').click();
    await page.locator('[data-hero-action="new"]').click();
    const defaults = await page.locator('#hero-editor input[type="number"]').evaluateAll(nodes => nodes.map(n => ({name: n.name, value: n.value})));
    for (const field of defaults) assert.equal(field.value, '0', `initial ${field.name}`);
    const values = { name: 'Gerard', culture: 'Elfowie z Lindonu', calling: 'Przywódca', age: '111', strength: '4', strengthTN: '16', heart: '4', heartTN: '16', wits: '6', witsTN: '14', maxEndurance: '24', endurance: '24', maxHope: '12', hope: '9', parry: '18', distinctiveFeatures: 'Zdolności przywódcze, Bystrooki, Chyży', culturalBlessing: 'Na sposób elfów', shadowPath: 'Pokusa Władzy', rewards: 'Potężna broń (Łuk)', virtues: 'Gibkość', weapon0Name: 'Łuk', weapon0Damage: '4', weapon0Injury: '14', weapon0Load: '2', weapon0Notes: 'Broń dystansowa', armourName: 'Skórzany kubrak', armour: '2', equipment: 'Latarnia „Gwiazda Wieczorna”\nDwa ostre noże' };
    for (const [key, value] of Object.entries(values)) {
      const control = page.locator(`#hero-editor [name="${key}"]`);
      await control.fill(value);
      await control.press('Tab');
    }
    await page.locator('[name="combatBows"]').selectOption('2');
    await page.locator('[data-hero-action="battle"]').click();
    assert.match(await page.locator('#hero-battle-list').textContent(), /Rynsztunek: Łuk · obrażenia 4 · przebicie 14/);
    assert.match(await page.locator('#hero-battle-list').textContent(), /Łuki 2/);
    const battleButton = page.locator('#hero-editor [data-hero-action="battle"]');
    assert.equal(await battleButton.textContent(), 'Usuń z potyczki');
    page.once('dialog', dialog => dialog.dismiss());
    await battleButton.click();
    assert.equal(await page.locator('#hero-battle-list .hero-battle-card').count(), 1);
    page.once('dialog', dialog => dialog.accept());
    await battleButton.click();
    assert.equal(await page.locator('#hero-battle-list .hero-battle-card').count(), 0);
    assert.equal(await battleButton.textContent(), 'Dodaj do potyczki');
    assert.equal(await page.locator('[name="name"]').inputValue(), 'Gerard');
    assert.equal(await page.locator('#hero-editor [name="stance"]').count(), 0);
    await page.locator('.sheet-extra summary').click();
    await page.locator('[name="notes"]').fill('Zapisana notatka');
    await page.locator('[name="notes"]').press('Tab');
    await page.locator('[name="skillLore"]').selectOption('3');
    await page.locator('[name="skillLoreFavoured"]').check();
    await page.locator('[name="weary"]').check();
    await page.reload();
    await page.locator('[data-tab="heroes"]').click();
    for (const [key, value] of Object.entries(values)) assert.equal(await page.locator(`#hero-editor [name="${key}"]`).inputValue(), value, key);
    assert.equal(await page.locator('[name="notes"]').inputValue(), 'Zapisana notatka');
    assert.equal(await page.locator('[name="skillLore"]').inputValue(), '3');
    assert.equal(await page.locator('[name="skillLoreFavoured"]').isChecked(), true);
    assert.equal(await page.locator('[name="weary"]').isChecked(), true);
    await page.locator('[name="weary"]').uncheck();
    await page.locator('[name="skillLoreFavoured"]').uncheck();
    assert.equal(await page.evaluate(() => OneRingStore.getState().heroes[0].weary), false);
    assert.equal(await page.evaluate(() => OneRingStore.getState().heroes[0].skillLoreFavoured), false);
    const character = page.locator('[data-sheet-section="character"]');
    assert.equal(await character.evaluate(n => n.open), true);
    await character.locator('.sheet-character-title').click();
    assert.equal(await page.locator('[name="name"]').isVisible(), false);
    assert.equal(await battleButton.isVisible(), true);
    await battleButton.click();
    assert.equal(await character.evaluate(n => n.open), false);
    assert.equal(await battleButton.textContent(), 'Usuń z potyczki');
    await page.locator('[data-hero-action="new"]').click();
    assert.equal(await character.evaluate(n => n.open), false);
    await page.getByRole('tab', {name: 'Gerard', exact:true}).click();
    assert.equal(await character.evaluate(n => n.open), false);
    assert.equal(await battleButton.textContent(), 'Usuń z potyczki');
    page.once('dialog', dialog => dialog.accept());
    await battleButton.click();
    assert.equal(await character.evaluate(n => n.open), false);
    await character.locator('summary').press('Enter');
    assert.equal(await character.evaluate(n => n.open), true);
    const openSections = () => page.locator('[data-sheet-section]:not([data-sheet-section="character"])').evaluateAll(nodes => nodes.map(n => n.open));
    assert.deepEqual(await openSections(), [true, true, true]);
    await page.locator('[data-sheet-section="attributes"] > summary').click();
    await page.locator('[data-sheet-section="equipment"] > summary').click();
    assert.deepEqual(await openSections(), [false, true, false]);
    assert.equal(await page.locator('[name="strength"]').isVisible(), false);
    assert.equal(await page.locator('[name="equipment"]').isVisible(), false);
    await page.locator('[data-hero-action="new"]').click();
    assert.deepEqual(await openSections(), [false, true, false], 'new hero shares view state');
    await page.getByRole('tab', {name: 'Gerard', exact: true}).click();
    assert.deepEqual(await openSections(), [false, true, false], 'switching heroes retains view state');
    await page.locator('[data-sheet-section="gear"] > summary').focus();
    await page.locator('[data-sheet-section="gear"] > summary').press('Enter');
    assert.deepEqual(await openSections(), [false, false, false]);
    await page.locator('[data-tab="generator"]').click();
    await page.locator('[data-tab="heroes"]').click();
    assert.deepEqual(await openSections(), [false, false, false], 'navigation retains view state');
    for (const key of ['attributes', 'gear', 'equipment']) await page.locator(`[data-sheet-section="${key}"] > summary`).click();
    assert.deepEqual(await openSections(), [true, true, true]);
    assert.equal(await page.locator('[name="strength"]').inputValue(), '4');
    assert.equal(await page.locator('[name="weapon0Name"]').inputValue(), 'Łuk');
    await page.locator('#hero-editor').screenshot({ path: '/tmp/hero-sheet-desktop.png' });
    for (const width of [1024, 768, 700, 390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow at ${width}`);
      const clipped = await page.locator('#hero-editor input, #hero-editor select, #hero-editor textarea').evaluateAll(nodes => nodes.filter(n => n.getBoundingClientRect().width && n.getBoundingClientRect().right > innerWidth).map(n => n.name));
      assert.deepEqual(clipped, [], `clipped controls at ${width}`);
      if (width === 390) await page.locator('#hero-editor').screenshot({ path: '/tmp/hero-sheet-mobile.png' });
    }
    assert.deepEqual(errors, []);
    console.log('Hero sheet passed: fields, ratings, checkboxes, reload, desktop and 5 responsive widths.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
