const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  try {
    const page = await browser.newPage({viewport:{width:1280,height:800}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8765');
    assert.deepEqual(await page.locator('.tabs .tab:visible').allTextContents(), ['Drużyna','Przeciwnicy','Potyczka 0']);
    assert.equal(await page.locator('#heroes').isVisible(),true);
    assert.equal(await page.locator('.tabs .active').textContent(),'Drużyna');
    assert.deepEqual(await page.locator('.backup-actions button').allTextContents(),['Eksportuj bazę','Wgraj bazę']);
    assert.equal(await page.locator('.backup-actions > span').count(),0);
    await page.locator('[data-tab="map"]').click();
    assert.equal(await page.locator('#map-panel h3, #map-blank strong').count(),0);
    assert.equal(await page.locator('#map-panel .map-panel-help').textContent(),'Stwórz mapę, by zobaczyć dodanych uczestników');
    await page.locator('[data-tab="opponents"]').click();
    assert.equal(await page.locator('#library').isVisible(),true);
    await page.locator('[data-category="Własne"]').click();
    assert.equal(await page.locator('#library-empty').isVisible(),true);
    assert.equal(await page.locator('#library-empty').textContent(),'Wybierz inną kategorię lub stwórz przeciwnika.');
    assert.equal(await page.locator('#library-empty h3, #library-empty span').count(),0);
    await page.locator('[data-category="Orkowie"]').click();
    assert.equal(await page.locator('#generator').isVisible(),false);
    assert.equal(await page.locator('#category-filters .active').textContent(),'Orkowie');
    assert.equal(await page.locator('[data-category="Wszystkie"], #import-data, #export-data, #import-file').count(),0);
    assert.equal(await page.locator('#create-enemy').getAttribute('class'),'text-button');
    assert.equal(await page.locator('#export-backup, #restore-backup').count(),2);
    await page.locator('[data-category="Orkowie"]').click();
    assert.equal(await page.locator('#category-filters .active').count(),0);
    const catalogCount = await page.locator('.library-card').count();
    await page.locator('[data-category="Orkowie"]').click();
    assert.ok(await page.locator('.library-card').count() < catalogCount);
    await page.locator('#library-search').fill('ork');
    const names = await page.locator('.library-card h3').allTextContents();
    await page.locator('#create-enemy').click();
    await page.locator('#name').fill('Szkic przeciwnika');
    const beforeCancel = await page.evaluate(()=>JSON.stringify(OneRingStore.getState()));
    await page.getByRole('button',{name:'Anuluj',exact:true}).click();
    assert.equal(await page.locator('#library').isVisible(),true);
    assert.equal(await page.evaluate(()=>JSON.stringify(OneRingStore.getState())),beforeCancel);
    assert.equal(await page.locator('#library-search').inputValue(),'ork');
    assert.deepEqual(await page.locator('.library-card h3').allTextContents(),names);
    await page.locator('#create-enemy').click();
    assert.equal(await page.locator('#name').inputValue(),'Szkic przeciwnika');
    await page.locator('[data-tab="heroes"]').click();
    await page.locator('[data-tab="opponents"]').click();
    assert.equal(await page.locator('#library').isVisible(),true);
    await page.locator('#create-enemy').click();
    assert.equal(await page.locator('#name').inputValue(),'Szkic przeciwnika');
    await page.locator('[data-action="library"]').click();
    assert.equal(await page.locator('.library-card.is-saved h3').textContent(),'Szkic przeciwnika');
    await page.locator('[data-category="Własne"]').click();
    assert.equal(await page.locator('#category-filters .active').count(),0);
    assert.equal(await page.locator('.library-card').count(),catalogCount+1);
    assert.equal(await page.locator('.library-card[data-source="Własne"]').count(),1);
    await page.locator('#library-search').fill('Szkic przeciwnika');
    assert.equal(await page.locator('.library-card').count(),1);
    await page.locator('#library-search').fill('');
    await page.locator('.library-card.is-saved').getByRole('button',{name:'Szablon',exact:true}).click();
    assert.equal(await page.locator('#name').inputValue(),'Szkic przeciwnika');
    await page.locator('[data-action="battle"]').click();
    assert.equal(await page.locator('#map').isVisible(),true);
    assert.equal(await page.evaluate(()=>OneRingStore.getState().battle.length),1);
    await page.locator('[data-tab="opponents"]').click();
    await page.locator('[data-category="Orkowie"]').click();
    await page.evaluate(()=>window.scrollTo(0,600));
    const scroll = await page.evaluate(()=>scrollY);
    await page.locator('.library-card .edit').nth(0).evaluate(node=>node.click());
    await page.locator('#reset-form').click();
    assert.equal(await page.evaluate(()=>scrollY),scroll);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('#create-enemy').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:'/tmp/opponents-mobile.png',fullPage:true});
    await page.locator('#legacy-battle-link').click();
    assert.equal(await page.locator('#battle').isVisible(),true);
    assert.equal(await page.locator('[data-tab="battle"]').isVisible(),false);
    assert.equal(new URL(page.url()).hash,'#battle');
    assert.equal(await page.locator('#battle-list .battle-card').count(),1);
    await page.reload();
    assert.equal(await page.locator('#battle').isVisible(),true);
    await page.locator('[data-tab="heroes"]').click();
    assert.equal(await page.locator('#battle').isVisible(),false);
    assert.equal(new URL(page.url()).hash,'');
    await page.reload();
    assert.equal(await page.locator('#heroes').isVisible(),true);
    await page.locator('#legacy-battle-link').click();
    await page.goBack();
    assert.equal(await page.locator('#heroes').isVisible(),true);
    await page.goForward();
    assert.equal(await page.locator('#battle').isVisible(),true);
    assert.deepEqual(errors,[]);
    console.log('Opponents navigation passed');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
